{
 "title": "Pizza Dashboard",
 "description": "jwt-pizza-service metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Factory Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pizza_latency_ratio", "legendFormat": "Pizza Creation Latency" }
   ]
  },
  {
   "title": "Server Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "service_latency_ratio", "legendFormat": "Latency in ms" }
   ]
  },
  {
   "title": "Authentications per Minute",
   "type": "timeseries",
   "description": "Auth Success and Failure attempts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(auth_success_total[1m])", "legendFormat": "Authentication Success" },
    { "expr": "auth_fail_total", "legendFormat": "Authentication Fail" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "active_users_total", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(pizza_success_total[1m])", "legendFormat": "Pizzas Created per minute" },
    { "expr": "pizza_failure_total", "legendFormat": "Creation Failures" }
   ]
  },
  {
   "title": "Revenue per Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(pizza_revenue_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "gauge",
   "description": "Usage of CPU",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "rate(requests_GET_total[1m])", "legendFormat": "GET" },
    { "expr": "rate(requests_POST_total[1m])", "legendFormat": "POST" },
    {
     "expr": "rate(requests_DELETE_total[1m])",
     "legendFormat": "DELETE"
    },
    { "expr": "rate(requests_PUT_total[1m])", "legendFormat": "PUT" },
    { "expr": "rate(requests_PATCH_total[1m])", "legendFormat": "PATCH" },
    { "expr": "rate(requests_total{}[1m])", "legendFormat": "All Requests" }
   ]
  }
 ]
}